name       : liborcus
version    : 0.12.1
release    : 3
source     :
    - http://kohei.us/files/orcus/src/liborcus-0.12.1.tar.xz : d1b936c66944d23e1b2582d0e7129e44670052510d03f19fef644e9814ae2b9c
license    : MPL-2.0
component  : programming
summary    : Standalone file processing filters
description: |
    Orcus is a library that provides a collection of standalone file processing filters.  It is currently focused on providing filters for spreadsheet documents, but filters for other productivity application types (such as wordprocessor and presentation) are in consideration.
builddeps  :
    - pkgconfig(libixion-0.12)
    - pkgconfig(mdds-1.2)
    - pkgconfig(python3)
    - libboost-devel
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
