name       : liborcus
version    : 0.13.2
release    : 6
source     :
    - https://kohei.us/files/orcus/src/liborcus-0.13.2.tar.xz : 9eb69cdd636bdaea22c9073c9f480ebaae05ef62bd483d68c8d4c05af927ea43
license    : MPL-2.0
component  : programming
summary    : Standalone file processing filters
description: |
    Orcus is a library that provides a collection of standalone file processing filters.  It is currently focused on providing filters for spreadsheet documents, but filters for other productivity application types (such as wordprocessor and presentation) are in consideration.
builddeps  :
    - pkgconfig(libixion-0.13)
    - pkgconfig(mdds-1.2)
    - pkgconfig(python3)
    - libboost-devel
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
