name       : liborcus
version    : 0.17.2
release    : 23
source     :
    - https://gitlab.com/orcus/orcus/-/archive/0.17.2/orcus-0.17.2.tar.gz : 06fd552265029e960e04efd11fae5aef277ea4552e5d39ba6fa707aa7f37b251
license    : MPL-2.0
component  : programming.library
summary    : Standalone file processing filters
description: |
    Orcus is a library that provides a collection of standalone file processing filters.  It is currently focused on providing filters for spreadsheet documents, but filters for other productivity application types (such as wordprocessor and presentation) are in consideration.
builddeps  :
    - pkgconfig(libixion-0.17)
    - pkgconfig(mdds-2.0)
    - pkgconfig(python3)
    - libboost-devel
rundeps    :
    - libixion
    - devel : libixion-devel
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
