name       : liborcus
version    : 0.15.3
release    : 15
source     :
    - https://gitlab.com/orcus/orcus/-/archive/0.15.3/orcus-0.15.3.tar.bz2 : c138d428e33ef3e6419f086f46f5296241dc2dfef08f4b8260855124cb1cfda7
license    : MPL-2.0
component  : programming.library
summary    : Standalone file processing filters
description: |
    Orcus is a library that provides a collection of standalone file processing filters.  It is currently focused on providing filters for spreadsheet documents, but filters for other productivity application types (such as wordprocessor and presentation) are in consideration.
builddeps  :
    - pkgconfig(libixion-0.15)
    - pkgconfig(mdds-1.5)
    - pkgconfig(python3)
    - libboost-devel
rundeps    :
    - libixion
    - devel : libixion-devel
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
