name       : liborcus
version    : 0.11.2
release    : 1
source     :
    - http://kohei.us/files/orcus/src/liborcus-0.11.2.tar.xz : 6911dc65a4d8276e42d32764e9ebee920b325cf59cfa7070fc72744d43b259ad
license    : MPL-2.0
component  : programming
summary    : Standalone file processing filters
description: |
    Orcus is a library that provides a collection of standalone file processing filters.  It is currently focused on providing filters for spreadsheet documents, but filters for other productivity application types (such as wordprocessor and presentation) are in consideration.
builddeps  :
    - pkgconfig(libixion-0.11)
    - pkgconfig(mdds-1.2)
    - pkgconfig(python3)
    - libboost-devel
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
