name       : liborcus
version    : 0.13.4
release    : 11
source     :
    - https://gitlab.com/orcus/orcus/-/archive/0.13.4/orcus-0.13.4.tar.bz2 : 02de149763cfabeb6492e16a6f0f814ae56b92a41ca2f7f8e0439943ec4e5840
license    : MPL-2.0
component  : programming.library
summary    : Standalone file processing filters
description: |
    Orcus is a library that provides a collection of standalone file processing filters.  It is currently focused on providing filters for spreadsheet documents, but filters for other productivity application types (such as wordprocessor and presentation) are in consideration.
builddeps  :
    - pkgconfig(libixion-0.13)
    - pkgconfig(mdds-1.2)
    - pkgconfig(python3)
    - libboost-devel
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
