name       : liborcus
version    : 0.14.1
release    : 13
source     :
    - https://gitlab.com/orcus/orcus/-/archive/0.14.1/orcus-0.14.1.tar.bz2 : ae7123a6f3b7a2ac684997dddfb2dc7df70359f38aa7749c2d7dd3e5f92a8709
license    : MPL-2.0
component  : programming.library
summary    : Standalone file processing filters
description: |
    Orcus is a library that provides a collection of standalone file processing filters.  It is currently focused on providing filters for spreadsheet documents, but filters for other productivity application types (such as wordprocessor and presentation) are in consideration.
builddeps  :
    - pkgconfig(libixion-0.14)
    - pkgconfig(mdds-1.4)
    - pkgconfig(python3)
    - libboost-devel
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
