name       : liborcus
version    : 0.16.1
release    : 20
source     :
    - https://gitlab.com/orcus/orcus/-/archive/0.16.1/orcus-0.16.1.tar.bz2 : cc4fd01811e46b68ddeee5cce7fe6b2a9decb760b9f8ff534b418f0a2d1cea07
license    : MPL-2.0
component  : programming.library
summary    : Standalone file processing filters
description: |
    Orcus is a library that provides a collection of standalone file processing filters.  It is currently focused on providing filters for spreadsheet documents, but filters for other productivity application types (such as wordprocessor and presentation) are in consideration.
builddeps  :
    - pkgconfig(libixion-0.16)
    - pkgconfig(mdds-1.5)
    - pkgconfig(python3)
    - libboost-devel
rundeps    :
    - libixion
    - devel : libixion-devel
setup      : |
    %apply_patches
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
