name       : liborcus
version    : 0.13.3
release    : 9
source     :
    - https://kohei.us/files/orcus/src/liborcus-0.13.3.tar.xz : a4c604fc319092637827abf21c0f93f72559084062aba168632e5a1e30d0b741
license    : MPL-2.0
component  : programming
summary    : Standalone file processing filters
description: |
    Orcus is a library that provides a collection of standalone file processing filters.  It is currently focused on providing filters for spreadsheet documents, but filters for other productivity application types (such as wordprocessor and presentation) are in consideration.
builddeps  :
    - pkgconfig(libixion-0.13)
    - pkgconfig(mdds-1.2)
    - pkgconfig(python3)
    - libboost-devel
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check

